{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubediff.fullname" . }}-clusterrolebinding
  labels:
    app.kubernetes.io/name: {{ include "kubediff.name" . }}
    helm.sh/chart: {{ include "kubediff.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubediff.fullname" . }}-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kubediff.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
