apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubediff.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubediff.name" . }}
    helm.sh/chart: {{ include "kubediff.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: controller
    app: kubediff
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: controller
      app: kubediff
  template:
    metadata:
      labels:
        component: controller
        app: kubediff
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.extraAnnotations }}
{{ toYaml .Values.extraAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      serviceAccountName: {{ include "kubediff.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{ end }}
          args:
            - -config=/config/
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kubediff.fullname" . }}-configmap
      {{- if .Values.securityContext }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

