apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubediff.serviceAccountName" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "kubediff.name" . }}
    helm.sh/chart: {{ include "kubediff.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
